FROM ubuntu:latest

RUN apt update -y
RUN apt upgrade -y
RUN apt-get update
RUN apt-get upgrade

RUN apt-get install nano
RUN apt install net-tools
RUN apt install dnsutils -y
RUN apt-get install iputils-ping -y
RUN apt install samba -y
RUN apt-get install smbclient -y
RUN apt install cifs-utils -y
RUN apt install lynx -y

CMD tail -f /dev/null
